export const CORE5_WEEVIL_BEHAVIOURS = Object.freeze({
  WALK: 0,
  JUMP: 1,
  WAVE1: 2,
  WAVE2: 3,
  SHAKE_HEAD: 4,
  NOD: 5,
  SQUAT: 6,
  STAND_TALL: 7,
  SIT_IN_CAR: 8,
  EXIT_CAR: 9,
  JUMP_TO: 10,
  THROW: 11,
  SPIN1: 12,
  SPIN2: 13,
  JIGGLE: 14,
  RIPPLE: 15,
  RIPPLE2: 16,
  RIPPLE3: 17,
  ARM_OUT1: 18,
  ARM_OUT2: 19,
  SHOW_VICTORY: 20,
  SKATE: 21,
  BOUNCE_TUMBLE: 22,
  TELEPORT: 23,
  HOLD_TRAY: 24,
  HOLD_ITEM: 25,
  ADD_ITEM_TO_TRAY: 26,
  REMOVE_ITEM_FROM_TRAY: 27,
  TELEPORT_OUT: 28,
  TELEPORT_IN: 29,
  GET_SPUN: 30,
  FLY_OUT: 31,
  DROP_IN: 32,
  SUPER_SPEED: 33,
  LEVEL_UP: 34,
  FLY_UP_TUBE: 35,
  SLIDE_OUT: 36,
  DROP_OUT: 37,
  SCENT_GLOW: 38,
  TAKE_HIT: 39,
  BECOME_GHOST: 40,
  BECOME_DISCO_BALL: 41,
  SLIDE: 42,
  BECOME_EATER_EGG: 43,
  BECOME_SEPIA: 44,
  BECOME_BUSH: 45,
  BECOME_BLACK: 46,
  BECOME_WHITE: 47,
  BECOME_FURBY_CRYSTAL: 48,
  BECOME_PUMPKIN: 49,
  BECOME_BAT: 50,
  TAKE_HIT2: 51,
  BECOME_SNOW_WEEVIL: 52,
  BECOME_TYCOON_HAT: 53,
  BECOME_SHARK_FIN: 54,
  BECOME_PERISCOPE: 55,
  BECOME_FROG: 56,
  BECOME_RUBBER_DUCK: 57,
  BECOME_COFFIN: 58,
  BECOME_DAISY: 59,
  BECOME_ANGRY_BIRDS: 60,
  BECOME_FURBY_CONNECT: 61,
  BECOME_FUTURE_WORM: 62,
  BECOME_TORCH_MARSHMALLOW: 63,
  BECOME_WEREWEEVIL: 64,
  BECOME_SMURFS_3_DRAGONFLY: 65,
  BECOME_PENGUIN: 66
});

export const CORE5_SPECIAL_MOVE_IDS = Object.freeze([
  23,
  40,
  41,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  61,
  62,
  63,
  64,
  65,
  66
]);

export const CORE5_BASIC_ACTION_IDS = Object.freeze({
  WALK: CORE5_WEEVIL_BEHAVIOURS.WALK,
  JUMP: CORE5_WEEVIL_BEHAVIOURS.JUMP,
  WAVE1: CORE5_WEEVIL_BEHAVIOURS.WAVE1,
  WAVE2: CORE5_WEEVIL_BEHAVIOURS.WAVE2,
  SHAKE_HEAD: CORE5_WEEVIL_BEHAVIOURS.SHAKE_HEAD,
  NOD: CORE5_WEEVIL_BEHAVIOURS.NOD,
  SQUAT: CORE5_WEEVIL_BEHAVIOURS.SQUAT,
  STAND_TALL: CORE5_WEEVIL_BEHAVIOURS.STAND_TALL
});

export function getCore5BehaviourName(id) {
  const numericId = Number(id);

  for (const [name, value] of Object.entries(CORE5_WEEVIL_BEHAVIOURS)) {
    if (value === numericId) {
      return name;
    }
  }

  return null;
}

export function isCore5SpecialMove(id) {
  return CORE5_SPECIAL_MOVE_IDS.includes(Number(id));
}
